#!/usr/bin/env bash

set -e

# ANSI escape code for red text
RED='\033[0;31m'
# ANSI escape code to reset text color
RESET='\033[0m'

if [ ! -d "port/image/root" ]; then
    mkdir -p "port/image/root"
    echo -e "${RED}created necessary directory${RESET}"
fi

if [ ! -d "port/image/tmp" ]; then
    mkdir -p "port/image/tmp"
    echo -e "${RED}created necessary directory${RESET}"
fi

make clean
make fs.img
make kernel/kernel && echo -e "${RED}generated kernel.bin${RESET}"

cd port/fip
./makefip.sh && echo -e "${RED}generated fip.bin${RESET}"

cd ../image
PATH=$PATH:/sbin
rm output/* -f
./makeimg.sh && echo -e "${RED}generated milkv-duo.img${RESET}"

sudo dd if=output/milkv-duo.img of=$1 status=progress &&
sync && echo -e "${RED}sd card burnt${RESET}"

